name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: Restore dependencies
      working-directory: ./Swordfish
      run: dotnet restore
    - name: Build
      working-directory: ./Swordfish
      run: dotnet build --no-restore --configuration Release
    - name: Test
      working-directory: ./Swordfish
      run: dotnet test --no-build --verbosity normal
